title: 基于虚拟仿真技术的移动英语课堂建设
logo: /assets/img/logo.png
description: 本项目结合游戏化学习与基于地理坐标的移动增强现实技术，借助移动便携设备内置的位置芯片提供的地理坐标信息，实现基于河南大学明伦校区校园环境的英语课堂。本实验教学项目构建了“一故事+五个场景”的实验教学流程。帮助学生浸入到语言应用的仿真环境中，更好地在目标语言的语境下了解我们的校园，在相互合作完成任务的同时，也增进彼此之间的了解，从而实现学生英语综合使用能力的提升。
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
